import os
import json
from helper_fts.logger import get_logger
import requests

logger = get_logger("OFD NAT")
obj_dict = {}
obj_dict["any"] = "Any"
# Palo
outnat = []
obj_dict = {}
tag_lst = []
PAN_DG = "/config/devices/entry[@name='localhost.localdomain']/device-group/entry"


###########################################
#         Checkpoint Functions            #
###########################################


def get_domain_list(cp):
    """This function will pull all the domain from Checkpoint.

    Args:
        cp (hadler): Handler to make specific API calls.
    """
    domain_list_data = []
    data = cp.show_domains()
    if data.status_code == 200:
        cp_data = json.loads(data.text)
        # Save all the domain into list - domain_list_data
        for domain_list in cp_data["objects"]:
            domain_list_data.append(domain_list["name"])
        return 0, domain_list_data
    return 1, data


def get_cma_packages_list(cp):
    """This function will pull all the package from specific Domain/CMA.

    Args:
        cp (hadler): Handler to make specific API calls.
    """
    data1 = {}
    data = {"limit": 500, "offset": 0, "details-level": "full"}
    data1["data"] = data
    data = cp.get_cp_data("show-packages", **data1)
    table_data = []
    if data.status_code == 200:
        cp_data = json.loads(data.text)
        for pkg_list in cp_data["packages"]:
            # This function will pull nat rulebase associated to the package in Domain/CMA
            if "all" in pkg_list["installation-targets"]:
                target = "All"
            else:
                install_targets = []
                for device in pkg_list["installation-targets"]:
                    install_targets.append(device["name"])
                target = ", ".join(install_targets)
            table_data.append(get_nat_rulebase(cp, pkg_list["name"], target))
        return table_data


def parse_data(cp, pkg, cp_data, trg):
    """This function will parse the rule.

    Args:
        cp (hadler): Handler to make specific API calls.
        pkg (str): CheckPoint Package Name.
        cp_data (dict): Firewall Rules.
    """
    uid_map = {}
    table_data = []
    # if "objects-dictionary" in cp_data:
    if cp_data.get("objects-dictionary"):
        # for obj_dict in cp_data["objects-dictionary"]:
        for obj_dict in cp_data.get("objects-dictionary"):
            # if "host" in obj_dict["type"]:
            if "host" in obj_dict.get("type"):
                if obj_dict.get("ipv4-address"):
                    # uid_map[obj_dict["uid"]] = obj_dict["ipv4-address"]
                    uid_map[obj_dict.get("uid")] = obj_dict.get("ipv4-address")
                else:
                    logger.info(f"{obj_dict}")
            elif "address-range" in obj_dict["type"]:
                uid_map[obj_dict["uid"]] = f"{obj_dict['ipv4-address-first']}-{obj_dict['ipv4-address-last']}"
            elif "network" in obj_dict["type"]:
                uid_map[obj_dict["uid"]] = f"{obj_dict['subnet4']}/{obj_dict['subnet-mask']}"
            else:
                uid_map[obj_dict["uid"]] = obj_dict["name"]
    for rule_dict in cp_data["rulebase"]:
        # these are NAT rules with sections
        if "rulebase" in rule_dict:
            for rule_dict1 in rule_dict["rulebase"]:
                if "static" in rule_dict1["method"]:
                    # these are Static rule
                    if "Any" not in uid_map.get(rule_dict1["original-source"]) or "Original" not in uid_map.get(
                        rule_dict1["original-source"]
                    ):
                        # these are Static rule but engineer created
                        if rule_dict1["auto-generated"] == False:
                            table_data.append(nat_var(rule_dict1, uid_map, pkg, trg))
                        else:
                            # these are Static rule autogenerated when object NAT is created
                            try:
                                data = {}
                                data["name"] = rule_dict1["original-source"]
                                data2 = {"data": data}
                                data1 = cp.get_cp_data("show-host", **data2)
                                cp_data1 = json.loads(data1.text)
                                if "nat-settings" in cp_data1:
                                    table_data.append(
                                        {
                                            "Method": rule_dict1["method"],
                                            "Original-Source": cp_data1["ipv4-address"],
                                            "Translated-Source": cp_data1["nat-settings"]["ipv4-address"],
                                            "Firewall": "CheckPoint",
                                            "Firewall-Name": trg,
                                            "Policy": pkg,
                                        }
                                    )
                            except:
                                table_data.append(nat_var(rule_dict1, uid_map, pkg, trg))
                elif "hide" in rule_dict1["method"]:
                    table_data.append(nat_var(rule_dict1, uid_map, pkg, trg))
        else:
            if "static" in rule_dict["method"]:
                if "Any" not in uid_map.get(rule_dict["original-source"]):
                    table_data.append(nat_var(rule_dict, uid_map, pkg, trg))
            else:
                table_data.append(nat_var(rule_dict, uid_map, pkg, trg))
    return table_data


def nat_var(rule_dict1, uid_map, pkg, trg):
    """Variable function.

    Args:
        uid_map (dict): UID to IP address.
        pkg (str): CheckPoint Package Name.
        rule_dict1 (dict): Firewall Rules.
    """
    var = {
        "Method": rule_dict1["method"],
        "Original-Source": uid_map.get(rule_dict1["original-source"]),
        "Translated-Source": uid_map.get(rule_dict1["translated-source"]),
        "Original-Destination": uid_map.get(rule_dict1["original-destination"]),
        "Translated-Destination": uid_map.get(rule_dict1["translated-destination"]),
        "Firewall": "CheckPoint",
        "Firewall-Name": trg,
        "Policy": pkg,
    }
    return var


def get_nat_rulebase(cp, pkg, trg):
    """To pull NAT Rulebase for given Package.

    Args:
        cp (hadler): Handler to make specific API calls.
        pkg (str): CheckPoint Package Name.
    """
    j = 0
    table_data = []
    total_rule = 0
    while j <= total_rule:
        data = {}
        data["limit"] = 500
        data["offset"] = 0 + j
        data["details-level"] = "standard"
        data["use-object-dictionary"] = "true"
        data["package"] = pkg
        data2 = {"data": data}
        data1 = cp.get_cp_data("show-nat-rulebase", **data2)
        if data1.status_code == 200:
            cp_data = json.loads(data1.text)
            total_rule = cp_data["total"]
        if total_rule == 0:
            j = j + 1
        else:
            table_data.extend(parse_data(cp, pkg, cp_data, trg))
            j = j + 500
    logger.info(f"\t\tPackages : {(pkg)} ({total_rule})")
    return table_data


###########################################
#           PaloAlto Functions            #
###########################################


def get_gp_lst(pan, xpaths):
    """Get the Object group list from Panorama and parase those object groups.

    Args:
        pan (hadler): Handler to make specific API calls.
        xpath (str): URI.
    """
    kwargs = {}
    kwargs["type"] = "config"
    kwargs["action"] = "get"
    kwargs["xpath"] = xpaths
    resp = pan.get_pam_data(**kwargs)

    if resp["response"]["result"] is None or resp["response"]["result"]["address-group"] is None:
        pass
    else:
        for obj in resp["response"]["result"]["address-group"]["entry"]:
            if "static" in obj:
                obj1_lst = []
                if obj != "static":
                    if isinstance(obj["static"]["member"], str):
                        if obj["static"]["member"] in obj_dict.keys():
                            obj_dict[obj["@name"]] = obj_dict[obj["static"]["member"]]
                        else:
                            obj_dict[obj["@name"]] = obj["static"]["member"]
                    else:
                        for member in obj["static"]["member"]:
                            if member in obj_dict.keys():
                                obj1_lst.append(obj_dict[member])
                            else:
                                obj1_lst.append(member)
                        obj_dict[obj["@name"]] = ",".join(obj1_lst)
            elif "dynamic" in obj:
                obj1_lst = []
                tmp = []
                for i in tag_lst:
                    if obj != "dynamic":
                        if " or " in obj["dynamic"]["filter"]:
                            tmp = obj["dynamic"]["filter"].split(" or ")
                        else:
                            tmp = obj["dynamic"]["filter"].split(" and ")
                        if obj["dynamic"]["filter"].strip("'") in i["tag"]:
                            obj1_lst.append(i["address"])
                        for x in tmp:
                            if str(x).strip("'") in i["tag"]:
                                obj1_lst.append(i["address"])
                        obj_dict[obj["@name"]] = ",".join(obj1_lst)


def search_list(source):
    """Get the Objects IPs.

    Args:
        source (dict): IP Dict.
    """
    s_lst = []
    if isinstance(source, list):
        for i in source:
            if i in obj_dict.keys():
                s_lst.append(obj_dict[i])
    else:
        if source in obj_dict.keys():
            s_lst.append(obj_dict[source])
    return s_lst


def get_device_group_lst(pan):
    """Get Device group list from Panorama.

    Args:
        pan (hadler): Handler to make specific API calls.
    """
    dg_lst = []
    kwargs = {}
    kwargs["type"] = "op"
    kwargs["cmd"] = "<show><devicegroups></devicegroups></show>"
    resp = pan.get_pam_data(**kwargs)
    for dev in resp["response"]["result"]["devicegroups"]["entry"]:
        if "devices" in dev:
            if isinstance(dev["devices"]["entry"], list):
                dev1 = []
                for j in dev["devices"]["entry"]:
                    dev1.append(j["hostname"])
                dg_lst.append({"device": dev["@name"], "hostname": ", ".join(dev1)})
            else:
                dg_lst.append({"device": dev["@name"], "hostname": dev["devices"]["entry"]["hostname"]})
    return dg_lst


def append_rule(rule, site, dg):
    """Write all the rules to file.

    Args:
        rule (str): Rule which need to be parsed and written to csv.
        site (str): PAN region info.
        dg (dict): Device group.
    """
    st_lst = []
    dt_lst = []
    method = None
    src_lst = search_list(rule["source"]["member"])
    if not src_lst:
        src_lst.append(rule["source"]["member"])

    dst_lst = search_list(rule["destination"]["member"])
    if not dst_lst:
        dst_lst.append(rule["destination"]["member"])

    if "source-translation" in rule.keys():
        if "dynamic-ip-and-port" in rule["source-translation"].keys():
            if "interface-address" in rule["source-translation"]["dynamic-ip-and-port"].keys():
                st_lst.append(rule["source-translation"]["dynamic-ip-and-port"]["interface-address"]["interface"])
                method = "source-dynamic-interface"
            if "translated-address" in rule["source-translation"]["dynamic-ip-and-port"].keys():
                st_lst = search_list(rule["source-translation"]["dynamic-ip-and-port"]["translated-address"]["member"])
                if st_lst == []:
                    st_lst.append(rule["source-translation"]["dynamic-ip-and-port"]["translated-address"]["member"])
                method = "source-dynamic-address"
        if "static-ip" in rule["source-translation"].keys():
            st_lst = search_list(rule["source-translation"]["static-ip"]["translated-address"])
            if st_lst == []:
                st_lst.append(rule["source-translation"]["static-ip"]["translated-address"])
            method = "source-static"
        if "dynamic-ip" in rule["source-translation"].keys():
            st_lst = search_list(rule["source-translation"]["dynamic-ip"]["translated-address"]["member"])
            if st_lst == []:
                st_lst.append(rule["source-translation"]["dynamic-ip"]["translated-address"]["member"])
            method = "source-dynamic-ip"

    if "dynamic-destination-translation" in rule.keys():
        dt_lst = search_list(rule["dynamic-destination-translation"]["translated-address"])
        if dt_lst == []:
            dt_lst.append(rule["dynamic-destination-translation"]["translated-address"])
        method = "dynamic-destination"

    if "destination-translation" in rule.keys():
        dt_lst = search_list(rule["destination-translation"]["translated-address"])
        if dt_lst == []:
            dt_lst.append(rule["destination-translation"]["translated-address"])
        method = "static-destination"

    outnat.append(
        {
            "Firewall": f"Palo Alto-{site}",
            "Policy": str(dg["device"]),
            "Original-Source": ", ".join(map(str, src_lst)),
            "Original-Destination": ", ".join(map(str, dst_lst)),
            "Method": method,
            "Firewall-Name": str(dg["hostname"]),
            "Translated-Source": ", ".join(map(str, st_lst)),
            "Translated-Destination": ", ".join(map(str, dt_lst)),
        }
    )


def get_nat_lst(pan, xpaths, site, dg):
    """Rulebase nat list.

    Args:
        xpaths (str): xpath for APIClient.
        dg (dict): device group.
        pan (hadler): Handler to make specific API calls.
        xpath (str): URI.
    """
    kwargs = {}
    kwargs["type"] = "config"
    kwargs["action"] = "get"
    kwargs["xpath"] = xpaths
    resp = pan.get_pam_data(**kwargs)
    if resp["response"]["result"] is not None:
        if resp["response"]["result"]["nat"]["rules"] is not None:
            if resp["response"]["result"]["nat"]["rules"]["entry"] is not None:
                ru = resp["response"]["result"]["nat"]["rules"]["entry"]
                if isinstance(ru, list):
                    for rule in ru:
                        if "disabled" not in rule:
                            append_rule(rule, site, dg)
                else:
                    if "disabled" not in ru:
                        append_rule(ru, site, dg)


def get_address(pan, xpaths):
    """Get the Object list from Panorama and parase those objects.

    Args:
        xpaths (str): xpath for APIClient.
        pan (hadler): Handler to make specific API calls.
    """
    kwargs = {}
    kwargs["type"] = "config"
    kwargs["action"] = "get"
    kwargs["xpath"] = xpaths
    resp = pan.get_pam_data(**kwargs)
    if resp["response"]["result"] is None or resp["response"]["result"]["address"] is None:
        pass
    else:
        if isinstance(resp["response"]["result"]["address"]["entry"], list):
            for obj in resp["response"]["result"]["address"]["entry"]:
                if "ip-netmask" in obj:
                    obj_dict[obj["@name"]] = obj["ip-netmask"]
                    if "tag" in obj and obj["tag"] is not None:
                        tag_lst.append(
                            {"name": obj["@name"], "address": obj["ip-netmask"], "tag": obj["tag"]["member"]}
                        )
                elif "ip-range" in obj:
                    obj_dict[obj["@name"]] = obj["ip-range"]
                    if "tag" in obj:
                        tag_lst.append({"name": obj["@name"], "address": obj["ip-range"], "tag": obj["tag"]["member"]})
                elif "fqdn" in obj:
                    obj_dict[obj["@name"]] = obj["fqdn"]
                    if "tag" in obj:
                        tag_lst.append({"name": obj["@name"], "address": obj["fqdn"], "tag": obj["tag"]["member"]})
        else:
            if "ip-netmask" in resp["response"]["result"]["address"]["entry"]:
                obj_dict[resp["response"]["result"]["address"]["entry"]["@name"]] = resp["response"]["result"][
                    "address"
                ]["entry"]["ip-netmask"]
                if "tag" in resp["response"]["result"]["address"]["entry"]:
                    tag_lst.append(
                        {
                            "name": resp["response"]["result"]["address"]["entry"]["@name"],
                            "address": resp["response"]["result"]["address"]["entry"]["ip-netmask"],
                            "tag": resp["response"]["result"]["address"]["entry"]["tag"]["member"],
                        }
                    )
            elif "ip-range" in resp["response"]["result"]["address"]["entry"]:
                obj_dict[resp["response"]["result"]["address"]["entry"]["@name"]] = resp["response"]["result"][
                    "address"
                ]["entry"]["ip-range"]
                if "tag" in resp["response"]["result"]["address"]["entry"]:
                    tag_lst.append(
                        {
                            "name": resp["response"]["result"]["address"]["entry"]["@name"],
                            "address": resp["response"]["result"]["address"]["entry"]["ip-range"],
                            "tag": resp["response"]["result"]["address"]["entry"]["tag"]["member"],
                        }
                    )


###########################################
#              File Upload                #
###########################################


def uploadfile(fname):
    """Upload file to remote server.

    Args:
        filename (str): Filename which need to be uploaded
    """

    url = "https://sas-automation.1dc.com/cgi-bin/uploadfile.py"
    files = [("filename", (os.path.basename(fname), open(fname, "rb")))]
    response = requests.request("POST", url, files=files, verify=False)
    return response.text
